export const productdata = {
  electronics: [
    {
      id: 1,
      name: "Smartphone",
      brand: "TechBrand",
      model: "XPhone 12",
      price: 799.99,
      features: {
        screen_size: "6.1 inches",
        battery_life: "24 hours",
        camera: "12 MP",
        storage: "128 GB",
      },
      warranty: "2 years",
    },
    {
      id: 2,
      name: "Laptop",
      brand: "CompTech",
      model: "UltraBook Pro",
      price: 1299.99,
      features: {
        screen_size: "15.6 inches",
        battery_life: "10 hours",
        processor: "Intel i7",
        ram: "16 GB",
        storage: "512 GB SSD",
      },
      warranty: "1 year",
    },
    {
      id: 3,
      name: "Tablet",
      brand: "TabCorp",
      model: "TabX 10",
      price: 499.99,
      features: {
        screen_size: "10.5 inches",
        battery_life: "12 hours",
        camera: "8 MP",
        storage: "256 GB",
      },
      warranty: "1 year",
    },
    {
      id: 4,
      name: "Smartwatch",
      brand: "WearTech",
      model: "WatchPro 3",
      price: 199.99,
      features: {
        screen_size: "1.5 inches",
        battery_life: "48 hours",
        heart_rate_monitor: true,
        gps: true,
      },
      warranty: "1 year",
    },
    {
      id: 5,
      name: "Bluetooth Speaker",
      brand: "SoundWave",
      model: "BoomBox 2",
      price: 149.99,
      features: {
        battery_life: "20 hours",
        waterproof: true,
        bluetooth_range: "30 feet",
        output_power: "20W",
      },
      warranty: "6 months",
    },
  ],
};
